name: Docker

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: filecoin/lily-archiver
        tags: |
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v2
      with:
        install: true

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
